### ISSUE TITLE
MSRV broken again in CI by dependencies

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2curves#112]
If you check https://github.com/privacy-scaling-explorations/halo2curves/actions/runs/7192434158/job/19596041204?pr=111#step:5:25

A bump in `colored` package causing:
```
error: package `colored v2.1.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.67.0
```

We should consider bumping the MSRV again..

**Comment by davidnevadoc** [comment]
Closed by #113
