### ISSUE TITLE
Add function in new_curve_impl has a wrong result

### ISSUE THREAD

**Issue by onurinanc** [privacy-scaling-explorations/halo2curves#115]
The following code snippet which does G + G + G + G = 4G and (G + G) + (G + G) = 4G gives different results for the Add function for the projective representation in here: https://github.com/privacy-scaling-explorations/halo2curves/blob/c7f8867f4234454a059b45b4872295dc10258755/src/derive/curve.rs#L997

```rust
let generator: G1 = G1::generator();
let generator_two = generator.add(generator);
let generator_three = generator_two.add(generator);
let generator_four = generator_three.add(generator);

println!("G1 generator is -> {:?}", generator);
println!("G1_two is -> {:?}", generator_two);
println!("G1_three is -> {:?}", generator_three);
println!("G1_four is -> {:?}", generator_four);

let res = generator_two.add(generator_two);
println!("G1_four double is -> {:?}", res);
```

**Comment by kilic** [comment]
@onurinanc Jacobian coordinates may not excatly match but they are indeed equal. You can see conversion rules [here](https://www.hyperelliptic.org/EFD/g1p/auto-shortw.html)

```
assert_eq!(res, generator_four);
println!("{:?}", generator_four.to_affine());
println!("{:?}", res.to_affine());
```
