### ISSUE TITLE
Remove `multicore` feature from `msm` bench

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2curves#126]
```
[[bench]]
name = "msm"
harness = false
required-features = ["multicore"]
```

Seems like we had a leftover feature for msm benchs

_Originally posted by @kilic in https://github.com/privacy-scaling-explorations/halo2curves/pull/122#discussion_r1447049332_

**Comment by duguorong009** [comment]
@CPerezz @kilic 
Can we merge the PR #127?

Whenever I try the release build for testing, it does show the following warning.
```
warning: invalid feature `multicore` in required-features of target `msm`: `multicore` is not present in [features] section
```
I am sure the PR is ready for merge(got the approval).
