### ISSUE TITLE
Sync with pasta_curves 0.5.0

### ISSUE THREAD

**Issue by kilic** [privacy-scaling-explorations/halo2curves#18]

**Comment by CPerezz** [comment]
While porting `secp256k1` I noticed the following:
Now `PrimeField` requires to be passed `MULTIPLICATIVE_GENERATOR` and `ROOT_OF_UNITY`.

MulGen is easy to derive using in Sage:
```
sage: GF(0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f).primitive_element()
3
```

From this, we should be able to derive the Root of Unity. By doing:
```
sage: mul_gen = Zp(3)
sage: root_unity = Zp((mul_gen^(modulus -1)))
sage: root_unity
1
```

This means, that `INV_ROOT_UNITY` which was equal to 0 previously in the implementation was wrong as it should be `1`. 

Currently investigating this.
