### ISSUE TITLE
Implement SerdeObject for pasta curves

### ISSUE THREAD

**Issue by alexander-camuto** [privacy-scaling-explorations/halo2curves#23]
Hey all ! 

Recent changes in https://github.com/privacy-scaling-explorations/halo2/pull/111 have greatly improved serialization performance, which is great ! However as `halo2curves::pasta::Fp` etc... do not currently implement `SerdeObject` it can make serializing `VerifyingKey` when using pasta curves kind of difficult.  

Are there any plans in motion to implement `SerdeObject` on said curve structs ? If not happy to give it a go.

**Comment by CPerezz** [comment]
For `pasta-curves` we haven't thought about it yet as we don't use them. So we were mainly re-exporting those only. 
But will comment with @kilic as he maybe has some ideas in mind.

**Comment by CPerezz** [comment]
Working on this. Should have a PR soon
