### ISSUE TITLE
Unimplemented hash to curve

### ISSUE THREAD

**Issue by GhostOfGauss** [privacy-scaling-explorations/halo2curves#32]
Currently the halo2 `CurveExt` trait is not fully implemented except for the pasta curves. The missing function `hash_to_curve` is unimplemented (see [here](https://github.com/privacy-scaling-explorations/halo2curves/blob/152fce6105f4cb813e83c52831e68148976b3982/src/derive/curve.rs#L557)). The implementation for pasta curves ([here](https://github.com/zcash/pasta_curves/blob/7e3fc6a4919f6462a32b79dd226cb2587b7961eb/src/curves.rs#L881)) makes use of an algorithm valid only for curves with `a*b = 0` (see [here](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-10.html#name-simplified-swu-for-ab-0-2)). This implementation should therefore work for bn256 and secp256k1, which both have `a = 0`.

My first attempt to copy-paste the pasta implementation over gets stuck on the `alloc` dependency. Once that's figured out I'd be happy to open a PR

**Comment by eldenpark** [comment]
I'd also like to know how this is going to be handled. Have you made any progress w/ that `alloc` feature? @GhostOfGauss

**Comment by han0110** [comment]
Replaced by #70
