### ISSUE TITLE
Floating point values truncated when exporting with serde_json

### ISSUE THREAD

**Issue by JSeam2** [privacy-scaling-explorations/halo2curves#53]
Floating point values are truncated when exporting with serde, there may be other issues with parsing long floating point values. There should be an option for users to enable for accurate floats if needed.

Here was one fix that we used within ezkl [https://github.com/zkonduit/ezkl/blob/main/src/graph/input.rs](https://github.com/zkonduit/ezkl/blob/main/src/graph/input.rs)

There was a need to explicitly map floating point values to f64 otherwise values gets truncated

Without custom Serialization, example
```
{"input_data": [[0.053262424, ... ]]}
```

With custom Serialization

```
data["input_data"] == [[0.05326242372393608, ...]]|
```

```rust
impl Serialize for GraphInput {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("GraphInput", 4)?;
        let input_data_f64: Vec<Vec<f64>> = self
            .input_data
            .iter()
            .map(|v| v.iter().map(|&f| f as f64).collect())
            .collect();
        let output_data_f64: Vec<Vec<f64>> = self
            .output_data
            .iter()
            .map(|v| v.iter().map(|&f| f as f64).collect())
            .collect();
        state.serialize_field("input_data", &input_data_f64)?;
        state.serialize_field("output_data", &output_data_f64)?;

        if let Some(processed_inputs) = &self.processed_inputs {
            state.serialize_field("processed_inputs", &processed_inputs)?;
        }

        if let Some(processed_params) = &self.processed_params {
            state.serialize_field("processed_params", &processed_params)?;
        }

        if let Some(processed_outputs) = &self.processed_outputs {
            state.serialize_field("processed_outputs", &processed_outputs)?;
        }
        state.end()
    }
}
```

Some other issues regarding large floats which is documented in this issue. There may be a need to enable to `float_roundtrip` flag to enable more accurate float parsing but this comes at an added processing time cost.

https://github.com/serde-rs/json/issues/536

**Comment by CPerezz** [comment]
Why instead of using Serde don't you modify `SerdeObject` & shennanigans to actually process floats as you need?

**Comment by JSeam2** [comment]
Looks like the flag is only on `serde_json` only and not `serde`, so this will be dependent on how end applications process the floating point values. Going to close the issue! Thanks for looking into it.

Hopefully, this issue could help someone who happens to stumble upon floating point representation and conversion issues!
