### ISSUE TITLE
feature request: Release halo2curves as a crate

### ISSUE THREAD

**Issue by huitseeker** [privacy-scaling-explorations/halo2curves#60]
[This page](https://crates.io/crates/halo2curves) is empty, which is sad:
![Screenshot 2023-07-04 at 10 56 28 AM](https://github.com/privacy-scaling-explorations/halo2curves/assets/4142/e289d6a0-1199-4f4a-b700-6414ec5720fb)
Please note the following piece in the Rust documentation (emphasis mine):

https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field

> Before you reach 1.0.0, **anything goes**, but if you make breaking changes, increment the minor version. In Rust, breaking changes include adding fields to structs or variants to enums.

Current rust versions of popular crates:
- nova is at 0.21.0,
- ff, group are at 0.13,
- bellperson is at 0.25,

From which I take that releasing a crate, especially if it is suitably marked as experimental in its Readme, is not a big commitment that has to impact the roadmap, or constrain the project. However, it is a huge boon in coordinating dependencies and synchronizing efforts in *using* the crate. It's also a way to get feedback through that actual usage of the project.

IOW, I hope halo2curves being released can actually make halo2curves *better*.

/cc @CPerezz @han0110 @davidnevadoc @kilic

**Comment by CPerezz** [comment]
Hey. I got news in regards the token to use for crates.io. Will publish the crate today/tomorrow. 
Will release it as 0.1.0

**Comment by CPerezz** [comment]
The Makefile fails to publish with: 
```
Enter passphrase for key '......': 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:privacy-scaling-explorations/halo2curves.git
 * [new tag]         v0.1.0 -> v0.1.0
cargo release publish --execute  --verbose
error: no such subcommand: `release`
make: *** [Makefile:16: release] Error 101
```

Idk why we have the `release` there. But is definitely wrong. 
Will do a PR ASAP. In any case, the thing is already in crates.io.

**Comment by CPerezz** [comment]
Closing this as completed. The crate is now live!
