### ISSUE TITLE
Makefile rule for publishing doesn't work

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2curves#61]
The Makefile fails to publish with: 
```
Enter passphrase for key '......': 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:privacy-scaling-explorations/halo2curves.git
 * [new tag]         v0.1.0 -> v0.1.0
cargo release publish --execute  --verbose
error: no such subcommand: `release`
make: *** [Makefile:16: release] Error 101
```

Idk why we have the `release` there. But is definitely wrong. 
Will do a PR ASAP. In any case, the thing is already in crates.io.

_Originally posted by @CPerezz in https://github.com/privacy-scaling-explorations/halo2curves/issues/60#issuecomment-1620559519_

**Comment by huitseeker** [comment]
The tool used for the publication of the crate is cargo-release, which you can install from there:
https://github.com/crate-ci/cargo-release
So in the Makefile, when you read "cargo release publish" is means "use the publish subcommand of the cargo-release tool". See ref here:
https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

Unfortunately, the `cargo-release` utility must be installed on the operator's machine (i.e.the person who runs the Makefile)

As `cargo-release` is used to prepare the release, this allows a few nice perks such as configuration-based setup of features passed to `cargo-publish`,  etc.

Please also note the TODOs of the release PR, which are still active (notably the tags):
https://github.com/privacy-scaling-explorations/halo2curves/pull/59
