### ISSUE TITLE
Tag update from `0.3.x -> 0.1.0` is breaking change

### ISSUE THREAD

**Issue by saiakilesh** [privacy-scaling-explorations/halo2curves#63]
Please update all PSE libs with updated version of `halo2curves` or bring back the `0.3.x` tags.

**Comment by han0110** [comment]
I've temperarily pushed back `0.3.x` tags for us to do the transition, in the future I guess we'd overwrite them when current new version reaches `0.3.x`.

@CPerezz and @huitseeker does the approach sound okay? I've checked the script and crates.io and didn't see issue for it yet, but still not 100% sure.

**Comment by CPerezz** [comment]
Sounds nice. I overwrote so that people moved to crates.io. But it's fine for me to actually proceed like this! <3
