### ISSUE TITLE
Make macros more modular to avoid performance drop when curve with `a = 0`

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/halo2curves#71]
In #54 we extend the macros to support curve with `a != 0`, but it also affects the performance for rest curves with `a = 0`, the performance drops is roughly like:

<img width="678" alt="2023-06-19_11 49 49" src="https://github.com/privacy-scaling-explorations/halo2curves/assets/24424538/e0d2c963-49dc-43f7-992f-8d9dbb252908">

We should make the macros more modular so the curves with `a = 0` could still benefit from the faster algorithm.

**Comment by mratsim** [comment]
In general, elliptic curve code can be specialized for
- a = 0
- a = -3 (all the NIST curves are in that case and it's the fastest for Jacobian coordinates)
- generic
