### ISSUE TITLE
The recent removal of pairings lib will make it difficult to update `halo2_proofs` and other libraries

### ISSUE THREAD

**Issue by alexander-camuto** [privacy-scaling-explorations/halo2curves#74]
The recent merge of https://github.com/privacy-scaling-explorations/halo2curves/pull/69 may make it very difficult to update `halo2_proofs` and other associated libraries, which are currently architected to depend on `halo2_curve` trait implementations (not `zkcrypto/pairing`). 

Recently gave a go at updating `halo2curves` in those repos and the number of cascading changes across repos is very large -- and the trait mismatches between `halo2_curves` and `zkcrypto/pairing` will make updating things a bit of a challenge. 

Just wanted to flag this as a potential maintainability challenge.

**Comment by CPerezz** [comment]
https://github.com/privacy-scaling-explorations/halo2/commit/f3487575f00e627705fcb7778d7d1049eed79601 was merged into `halo2` and no issues arised. 

|
Not sure I see the problem here.
