### ISSUE TITLE
Monitor upstream moves to CurveAffine

### ISSUE THREAD

**Issue by huitseeker** [privacy-scaling-explorations/halo2curves#75]
Consider:
https://github.com/zkcrypto/group/pull/48
https://github.com/zcash/pasta_curves/pull/75
Which may be relevant to the local integration of pasta curves, as well as the downstream integration in Nova ( https://github.com/microsoft/Nova/issues/198 ).

/cc @CPerezz

**Comment by CPerezz** [comment]
I spoke to @str4d today at ZCon and by chance we exactly spoke about better trait support for curve cycles. He said is working on this. And I'm curious to see his final design. What he told me so far looks nice. And looks something we definitely will benefit from. 

As soon as we get a new version of group, we will update all the macros accordingly!

Thanks for the ping!

**Comment by duguorong009** [comment]
@CPerezz Should we keep this issue open?

AFAIK, the mentioned PRs have not been merged at all.
The PRs(https://github.com/zkcrypto/group/pull/48, https://github.com/zcash/pasta_curves/pull/75) are still open, and I don't see any intention or movement to take care of them.
Also, https://github.com/microsoft/Nova/issues/198 is closed after some consideration. (https://github.com/microsoft/Nova/issues/198#issuecomment-1823704692)

What do you think? sir

**Comment by CPerezz** [comment]
Hey @duguorong009 i think we can close but not due to this, rather due to the fact that we are constantly checking this and writing the RFC proposal.

Thanks @huitseeker for the help on this, although closing, we will keep tracking ofc.

**Comment by duguorong009** [comment]
Thanks! @CPerezz 
I am sure you are indicating the correct reasons.
Can you close the issue with the appropriate comment?

**Comment by CPerezz** [comment]
@duguorong009 you should have permission to do so right?

In any case, Closing due to we're already monitoring. And for any updates we will file new issues  with concrete tasks.
